// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whoops.DataLayer;

namespace Whoops.Migrations
{
    [DbContext(typeof(WorldContext))]
    [Migration("20181207073231_roles")]
    partial class roles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Whoops.DataLayer.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Arrival");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longtitude");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<int?>("TripId");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("Whoops.DataLayer.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Name");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Whoops.DataLayer.UserInfo.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Remark");

                    b.Property<byte>("Stars");

                    b.HasKey("Id");

                    b.ToTable("FeedBack");
                });

            modelBuilder.Entity("Whoops.DataLayer.UserInfo.Loyalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentDiscount");

                    b.HasKey("Id");

                    b.ToTable("Loyalty");
                });

            modelBuilder.Entity("Whoops.DataLayer.UserInfo.UserHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActivityDate");

                    b.Property<double>("AmountPayed");

                    b.Property<int?>("CustomerFeedbackId");

                    b.Property<string>("OperatedBy");

                    b.Property<int?>("OperationistFeedbackId");

                    b.Property<string>("ProcedureName");

                    b.Property<string>("UserId");

                    b.HasKey("HistoryId");

                    b.HasIndex("CustomerFeedbackId");

                    b.HasIndex("OperationistFeedbackId");

                    b.ToTable("UserHistory");
                });

            modelBuilder.Entity("Whoops.DataLayer.Stop", b =>
                {
                    b.HasOne("Whoops.DataLayer.Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripId");
                });

            modelBuilder.Entity("Whoops.DataLayer.UserInfo.UserHistory", b =>
                {
                    b.HasOne("Whoops.DataLayer.UserInfo.FeedBack", "CustomerFeedback")
                        .WithMany()
                        .HasForeignKey("CustomerFeedbackId");

                    b.HasOne("Whoops.DataLayer.UserInfo.FeedBack", "OperationistFeedback")
                        .WithMany()
                        .HasForeignKey("OperationistFeedbackId");
                });
#pragma warning restore 612, 618
        }
    }
}
